### ISSUE TITLE
template cannot import to zabbix 3.2

### ISSUE THREAD

**Issue by litao941** [armahan/zabbix-templates#1]
Got the error as follow:
Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": unexpected tag "preprocessing".

**Comment by armagan-droid** [comment]
I will convert the template for Zabbix 3.2.
Thank you for information.

**Comment by alexdcx** [comment]
zabbix org.json.JSONException: JSONObject["conn"] not found.
