### ISSUE TITLE
QueueSize not supported

### ISSUE THREAD

**Issue by Djang0** [armahan/zabbix-templates#2]
Hi,

I manage make the jmx console work for activemq...
When most of the items seem to be activated, the queueSize item is not supported (see attached)
![image](https://user-images.githubusercontent.com/841633/43893428-3a91f75a-9bcf-11e8-9c9e-fde1b015c799.png)

Could it be that `jmx["org.apache.activemq:type=Destination,brokerName={$BRKNAME}",QueueSize]` is not a valid JMX query?

Activemq 5.14.3
Zabbix appliance 3.4

**Comment by armagan-droid** [comment]
Hi,
Did you check the queue via Jmx console?
If queue is empty,  It wont be a queue size.
I will check as soon as possible the template.

**Comment by Djang0** [comment]
I'm not sure how the templates are working (I'm new to zabbix) but I thought Zabbix would discover queues automatically and add a trigger for each queue discovered based on the {$AMQ_DESTINATION_QUEUE_SIZE_THRESHOLD} setting.

Does it mean I have to add a trigger by myself for each queue I want to monitor?

Through JMX console queues are available and somme have a lot of message in it ? 

![image](https://user-images.githubusercontent.com/841633/43897640-fcdb6a96-9bdc-11e8-8101-e7f9a311cd22.png)

**Comment by armagan-droid** [comment]
the link below will you help. https://www.zabbix.com/documentation/3.4/manual/discovery/low_level_discovery/jmx

**Comment by Djang0** [comment]
Thanks ! I just finished reading it and ok I understood that queues are actually "destinations".
But I don't understand why `jmx.discovery[beans,"org.apache.activemq:type=Destination,destinationName=*"]` (default from template) is "not supported " by zabbix.

![image](https://user-images.githubusercontent.com/841633/43900830-3b7f499e-9be6-11e8-8c14-3c467c5c5944.png)
